#!/usr/bin/env node

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const HARDHAT_TEMPLATE_PATH = join(__dirname, "../../fhevm-hardhat-template");
const OUTPUT_DIR = join(__dirname, "../abi");

function ensureDirectoryExists(dir) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function readDeployment(network, contractName) {
  const deploymentPath = join(
    HARDHAT_TEMPLATE_PATH,
    "deployments",
    network,
    `${contractName}.json`
  );

  if (!existsSync(deploymentPath)) {
    return null;
  }

  try {
    const deploymentData = JSON.parse(readFileSync(deploymentPath, "utf-8"));
    return {
      address: deploymentData.address,
      abi: deploymentData.abi,
    };
  } catch (error) {
    console.warn(`Warning: Failed to read ${deploymentPath}:`, error.message);
    return null;
  }
}

function generateABIFile(contractName, abi) {
  const content = `// Auto-generated by genabi.mjs
// Do not edit manually

export const ${contractName}ABI = ${JSON.stringify(abi, null, 2)} as const;
`;

  const outputPath = join(OUTPUT_DIR, `${contractName}ABI.ts`);
  writeFileSync(outputPath, content, "utf-8");
  console.log(`✓ Generated ${contractName}ABI.ts`);
}

function generateAddressFile(contractName, addresses) {
  const content = `// Auto-generated by genabi.mjs
// Do not edit manually

export const ${contractName}Addresses: Record<number, string> = ${JSON.stringify(addresses, null, 2)};
`;

  const outputPath = join(OUTPUT_DIR, `${contractName}Addresses.ts`);
  writeFileSync(outputPath, content, "utf-8");
  console.log(`✓ Generated ${contractName}Addresses.ts`);
}

function main() {
  console.log("🔄 Generating ABI files from deployments...\n");

  ensureDirectoryExists(OUTPUT_DIR);

  const CONTRACT_NAME = "FringeStageVote";
  const NETWORKS = {
    localhost: 31337,
    sepolia: 11155111,
  };

  const addresses = {};
  let abi = null;

  for (const [network, chainId] of Object.entries(NETWORKS)) {
    const deployment = readDeployment(network, CONTRACT_NAME);

    if (deployment) {
      addresses[chainId] = deployment.address;
      if (!abi) {
        abi = deployment.abi;
      }
      console.log(`✓ Found ${CONTRACT_NAME} on ${network} (${chainId}): ${deployment.address}`);
    } else {
      console.log(`  Skipping ${network} (not deployed yet)`);
    }
  }

  // If no deployments found, try to use existing ABI file (for CI/CD builds)
  if (!abi) {
    const existingABIPath = join(OUTPUT_DIR, `${CONTRACT_NAME}ABI.ts`);
    if (existsSync(existingABIPath)) {
      console.log("\n⚠️  No deployments found, but existing ABI file exists.");
      console.log("   Using existing ABI file for build...");
      
      // Read existing addresses if available
      const existingAddressesPath = join(OUTPUT_DIR, `${CONTRACT_NAME}Addresses.ts`);
      if (existsSync(existingAddressesPath)) {
        try {
          const addressesContent = readFileSync(existingAddressesPath, "utf-8");
          // Extract addresses from the file (simple regex match)
          const addressesMatch = addressesContent.match(/Record<number, string> = ({[^}]+})/);
          if (addressesMatch) {
            const addressesObj = eval(`(${addressesMatch[1]})`);
            Object.assign(addresses, addressesObj);
            console.log("   Using existing address mappings");
          }
        } catch (e) {
          console.warn("   Could not parse existing addresses file");
        }
      }
      
      // Use hardcoded Sepolia address if no addresses found
      if (Object.keys(addresses).length === 0) {
        addresses[11155111] = "0xBa1580Fb2Ad8148BC73e220944b2E1C5fBCC9D3f";
        console.log("   Using hardcoded Sepolia address");
      }
      
      // Don't regenerate ABI, just update addresses if needed
      if (Object.keys(addresses).length > 0) {
        generateAddressFile(CONTRACT_NAME, addresses);
        console.log("\n✅ Address mapping updated!\n");
      } else {
        console.log("\n✅ Using existing files (no changes needed)\n");
      }
      return;
    } else {
      console.error("\n❌ Error: No deployments found and no existing ABI file.");
      console.error("   Please deploy the contract first:");
      console.error("   cd ../fhevm-hardhat-template");
      console.error("   npx hardhat deploy --network localhost");
      process.exit(1);
    }
  }

  console.log("\n📝 Writing ABI files...");
  generateABIFile(CONTRACT_NAME, abi);
  generateAddressFile(CONTRACT_NAME, addresses);

  console.log("\n✅ ABI generation complete!\n");
}

main();

