// Auto-generated by genabi.mjs
// Do not edit manually

export const FringeStageVoteAddresses: Record<number, string> = {
  "31337": "0xBa1580Fb2Ad8148BC73e220944b2E1C5fBCC9D3f",
  "11155111": "0xBa1580Fb2Ad8148BC73e220944b2E1C5fBCC9D3f"
};
