// Auto-generated by genabi.mjs
// Do not edit manually

export const FringeStageVoteABI = [
  {
    "inputs": [],
    "name": "AlreadyVoted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DecryptionAlreadyRequested",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientVotes",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRatingValue",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OnlyTheaterCompany",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SessionNotActive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SessionNotEnded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SessionNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SessionStillActive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedTheater",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZamaProtocolUnsupported",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "avgPlotTension",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "avgPerformance",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "avgStageDesign",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "avgPacing",
        "type": "uint16"
      }
    ],
    "name": "DecryptionCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "requester",
        "type": "address"
      }
    ],
    "name": "DecryptionRequested",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "venue",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "startTime",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "endTime",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "theaterCompany",
        "type": "address"
      }
    ],
    "name": "SessionCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "theaterAddress",
        "type": "address"
      }
    ],
    "name": "TheaterAuthorized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newVoteCount",
        "type": "uint256"
      }
    ],
    "name": "VoteSubmitted",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MIN_VOTES_FOR_DECRYPTION",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "theaterAddress",
        "type": "address"
      }
    ],
    "name": "authorizeTheater",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "confidentialProtocolId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "venue",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "startTime",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "endTime",
        "type": "uint256"
      }
    ],
    "name": "createSession",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      }
    ],
    "name": "endSession",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      }
    ],
    "name": "getDecryptedResults",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "totalPlotTension",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "totalPerformance",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "totalStageDesign",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "totalPacing",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "avgPlotTension",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "avgPerformance",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "avgStageDesign",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "avgPacing",
        "type": "uint16"
      },
      {
        "internalType": "uint256",
        "name": "voteCount",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      }
    ],
    "name": "getEncryptedAggregates",
    "outputs": [
      {
        "internalType": "euint16",
        "name": "plotTension",
        "type": "bytes32"
      },
      {
        "internalType": "euint16",
        "name": "performance",
        "type": "bytes32"
      },
      {
        "internalType": "euint16",
        "name": "stageDesign",
        "type": "bytes32"
      },
      {
        "internalType": "euint16",
        "name": "pacing",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      }
    ],
    "name": "getSessionInfo",
    "outputs": [
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "venue",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "startTime",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "endTime",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "theaterCompany",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "voteCount",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "isActive",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "decryptionRequested",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "decryptionCompleted",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getTotalSessions",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "voter",
        "type": "address"
      }
    ],
    "name": "hasVoted",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "theaterAddress",
        "type": "address"
      }
    ],
    "name": "isAuthorized",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      }
    ],
    "name": "requestDecryption",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "internalType": "uint16",
        "name": "totalPlotTension",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "totalPerformance",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "totalStageDesign",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "totalPacing",
        "type": "uint16"
      }
    ],
    "name": "storeDecryptedResults",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "internalType": "externalEuint16",
        "name": "inputPlotTension",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proofPlotTension",
        "type": "bytes"
      },
      {
        "internalType": "externalEuint16",
        "name": "inputPerformance",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proofPerformance",
        "type": "bytes"
      },
      {
        "internalType": "externalEuint16",
        "name": "inputStageDesign",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proofStageDesign",
        "type": "bytes"
      },
      {
        "internalType": "externalEuint16",
        "name": "inputPacing",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proofPacing",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "submitVote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
